name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3 #setup nodejs in our runner
      - run: npm install pm2@latest -g #install pm2 global

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd auto-deploy-flask
            git pull origin main
            git status
            pm2 reload AutoDeployFlask
            pm2 restart AutoDeployFlask
