name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd auto-deploy-flask
            git pull origin main
            git status

            source .auto/bin/activate

            pip install -r requirements.txt

            ps aux | grep gunicorn

            pkill -f '/usr/bin/gunicorn'

            gunicorn -w 3 -b 0.0.0.0:7001 app:app --daemon
