name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd auto-deploy-flask
            git pull origin main
            git status
            sudo ln -s "$NVM_DIR/versions/node/v20.15.1/bin/node" "/usr/local/bin/node"
            sudo ln -s "$NVM_DIR/versions/node/v20.15.1/bin/npm" "/usr/local/bin/npm"
            sudo ln -s "$NVM_DIR/versions/node/v20.15.1/bin/pm2" "/usr/local/bin/pm2"
            pm2 reload AutoDeployFlask
            pm2 restart AutoDeployFlask
